// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjQu6S1HQMpwtS0cIaUh_CN-ZcNECakvY',
    appId: '1:1061510269166:web:2980a0f563fcc2f3b14bff',
    messagingSenderId: '1061510269166',
    projectId: 'percobaan-tup3',
    authDomain: 'percobaan-tup3.firebaseapp.com',
    databaseURL: 'https://percobaan-tup3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'percobaan-tup3.firebasestorage.app',
    measurementId: 'G-X2WS7XV35T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGnkf6GeO_pqpWKnJo_m_Qyf4Sv6QdiPU',
    appId: '1:1061510269166:android:5cb0b557ee96d785b14bff',
    messagingSenderId: '1061510269166',
    projectId: 'percobaan-tup3',
    databaseURL: 'https://percobaan-tup3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'percobaan-tup3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeApfoRN-MINOgvLVxp8lb44Ug_16LOik',
    appId: '1:1061510269166:ios:73e0a498d33a024eb14bff',
    messagingSenderId: '1061510269166',
    projectId: 'percobaan-tup3',
    databaseURL: 'https://percobaan-tup3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'percobaan-tup3.firebasestorage.app',
    iosBundleId: 'com.example.smartBinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA05_cwSJ9oOXRxyJF6_QEkKc4SeWeOeQ4',
    appId: '1:1061510269166:web:0007c564676bd4cdb14bff',
    messagingSenderId: '1061510269166',
    projectId: 'percobaan-tup3',
    authDomain: 'percobaan-tup3.firebaseapp.com',
    databaseURL: 'https://percobaan-tup3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'percobaan-tup3.firebasestorage.app',
    measurementId: 'G-PPZD20DEDN',
  );
}
